"""
Pydantic request/response models for the classification API.
"""

from datetime import datetime
from pydantic import BaseModel, Field


class ClassifyRequest(BaseModel):
    """Request body for POST /classify."""
    publication_id: int = Field(..., description="ID of the publication in the main database")
    title: str = Field(..., description="Publication title")
    abstract_text: str = Field(..., description="Publication abstract text")
    domain: str | None = Field(None, description="Domain name chosen by the author")
    pdf_url: str | None = Field(None, description="URL of the PDF file for text extraction")


class PersonalizedRecommendationRequest(BaseModel):
    """Request body for POST /recommend/personalized."""
    upvotedIds: list[int]
    downvotedIds: list[int]
    limit: int = 10


class CategoryPrediction(BaseModel):
    category: str
    confidence: float
    reason: str


class ClassifyResponse(BaseModel):
    """Response body for POST /classify."""
    publication_id: int
    cluster_id: int
    cluster_label: str
    confidence: float = Field(..., ge=0.0, le=1.0, description="Cosine similarity to cluster centroid")
    categories: list[CategoryPrediction] = Field(default_factory=list, description="Categories predicted by Gemma 3")
    keywords: list[str] = Field(default_factory=list, description="Keywords generated by Gemma 3")
    suggested_cluster_id: int | None = Field(default=None, description="Soft-assigned cluster ID for UI if outlier.")
    suggested_cluster_label: str | None = Field(default=None, description="Soft-assigned cluster label for UI if outlier.")
    explainability_score: float | None = Field(default=None, description="Overlap score between paper keywords and cluster label/keywords")


class RecommendationResponse(BaseModel):
    """Response body for recommendation endpoints."""
    publication_id: int
    similarity_score: float
    cluster_id: int | None = None


class ClosePair(BaseModel):
    """Response body for close pair detection."""
    publication_1_id: int
    publication_2_id: int
    similarity_score: float


class ClusterInfo(BaseModel):
    """Information about a single cluster."""
    cluster_id: int
    label: str
    member_count: int


class ClusterDetail(BaseModel):
    """Detailed cluster info with member publication IDs."""
    cluster_id: int
    label: str
    member_count: int
    publication_ids: list[int]


class ReclusterResponse(BaseModel):
    """Response body for POST /recluster."""
    total_publications: int
    clusters_found: int
    noise_points: int
    # Extended stats (present after G3 fix)
    duration_seconds: float | None = Field(default=None, description="Wall-clock time for the run in seconds")
    id_matches_reused: int | None = Field(default=None, description="Clusters that kept their stable ID from the previous run")
    new_clusters: int | None = Field(default=None, description="Clusters assigned a brand-new ID (genuinely new topics)")
    pending_before: int | None = Field(default=None, description="Pending pool size before this run")
    pending_after: int | None = Field(default=None, description="Pending pool size after this run")


class ClusteringRunLogEntry(BaseModel):
    """One row from the clustering_run_log table."""
    id: int
    started_at: datetime
    finished_at: datetime
    duration_seconds: float | None = None
    total_publications: int | None = None
    clusters_before: int | None = None
    clusters_after: int | None = None
    new_clusters: int | None = None
    id_matches_reused: int | None = None
    noise_points: int | None = None
    pending_before: int | None = None
    pending_after: int | None = None


class HealthResponse(BaseModel):
    """Response body for GET /health."""
    status: str
    model_loaded: bool


class SubmitCorrectionRequest(BaseModel):
    """Request body for POST /corrections."""
    publication_id: int = Field(..., description="ID of the publication being corrected")
    assigned_cluster_id: int = Field(..., description="Cluster ID assigned by the algorithm")
    correct_cluster_id: int = Field(..., description="Correct cluster ID per human feedback")
    corrected_by: str = Field(default="unknown", description="Username or identifier of the corrector")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score for the correction")


class CorrectionResponse(BaseModel):
    """Response body for POST /corrections."""
    publication_id: int
    assigned_cluster_id: int
    correct_cluster_id: int
    corrected_by: str
    confidence: float
    exemplars_seeded: bool = Field(..., description="Whether exemplars were seeded for correct cluster")


class ClusterMetricsResponse(BaseModel):
    """Cluster metrics for a single cluster."""
    cluster_id: int
    intra_cluster_mean_similarity: float | None = None
    member_count: int | None = None
    correction_rate_30d: float | None = None
    pending_inflow_rate: float | None = None
    centroid_drift: float | None = None
    last_label_updated_at: datetime | None = None
    exemplar_coverage: float | None = None
    computed_at: datetime | None = None


class SystemConfig(BaseModel):
    """System configuration parameters."""
    SIMILARITY_THRESHOLD: float
    SOFT_SIMILARITY_THRESHOLD: float
    HDBSCAN_MIN_CLUSTER_SIZE: int
    STABLE_ID_SIMILARITY_THRESHOLD: float
    DYNAMIC_THRESHOLD_MULTIPLIER: float
    MIN_ASSIGNMENT_THRESHOLD: float
    MAX_ASSIGNMENT_THRESHOLD: float
    PENDING_RECLUSTER_ATTEMPTS: int
    RECLUSTER_MIN_NEW_PAPERS: int
    RECLUSTER_PENDING_THRESHOLD: int
    RECLUSTER_MAX_INTERVAL_HOURS: int
"""
Pydantic request/response models for the classification API.
"""

from datetime import datetime
from pydantic import BaseModel, Field


class ClassifyRequest(BaseModel):
    """Request body for POST /classify."""
    publication_id: int = Field(..., description="ID of the publication in the main database")
    title: str = Field(..., description="Publication title")
    abstract_text: str = Field(..., description="Publication abstract text")
    domain: str | None = Field(None, description="Domain name chosen by the author")
    pdf_url: str | None = Field(None, description="URL of the PDF file for text extraction")


class PersonalizedRecommendationRequest(BaseModel):
    """Request body for POST /recommend/personalized."""
    upvotedIds: list[int]
    downvotedIds: list[int]
    limit: int = 10


class CategoryPrediction(BaseModel):
    category: str
    confidence: float
    reason: str


class ClassifyResponse(BaseModel):
    """Response body for POST /classify."""
    publication_id: int
    cluster_id: int
    cluster_label: str
    confidence: float = Field(..., ge=0.0, le=1.0, description="Cosine similarity to cluster centroid")
    categories: list[CategoryPrediction] = Field(default_factory=list, description="Categories predicted by Gemma 3")
    keywords: list[str] = Field(default_factory=list, description="Keywords generated by Gemma 3")
    suggested_cluster_id: int | None = Field(default=None, description="Soft-assigned cluster ID for UI if outlier.")
    suggested_cluster_label: str | None = Field(default=None, description="Soft-assigned cluster label for UI if outlier.")
    explainability_score: float | None = Field(default=None, description="Overlap score between paper keywords and cluster label/keywords")


class RecommendationResponse(BaseModel):
    """Response body for recommendation endpoints."""
    publication_id: int
    similarity_score: float
    cluster_id: int | None = None


class ClosePair(BaseModel):
    """Response body for close pair detection."""
    publication_1_id: int
    publication_2_id: int
    similarity_score: float


class ClusterInfo(BaseModel):
    """Information about a single cluster."""
    cluster_id: int
    label: str
    member_count: int


class ClusterDetail(BaseModel):
    """Detailed cluster info with member publication IDs."""
    cluster_id: int
    label: str
    member_count: int
    publication_ids: list[int]


class ReclusterResponse(BaseModel):
    """Response body for POST /recluster."""
    total_publications: int
    clusters_found: int
    noise_points: int
    # Extended stats (present after G3 fix)
    duration_seconds: float | None = Field(default=None, description="Wall-clock time for the run in seconds")
    id_matches_reused: int | None = Field(default=None, description="Clusters that kept their stable ID from the previous run")
    new_clusters: int | None = Field(default=None, description="Clusters assigned a brand-new ID (genuinely new topics)")
    pending_before: int | None = Field(default=None, description="Pending pool size before this run")
    pending_after: int | None = Field(default=None, description="Pending pool size after this run")


class ClusteringRunLogEntry(BaseModel):
    """One row from the clustering_run_log table."""
    id: int
    started_at: datetime
    finished_at: datetime
    duration_seconds: float | None = None
    total_publications: int | None = None
    clusters_before: int | None = None
    clusters_after: int | None = None
    new_clusters: int | None = None
    id_matches_reused: int | None = None
    noise_points: int | None = None
    pending_before: int | None = None
    pending_after: int | None = None


class HealthResponse(BaseModel):
    """Response body for GET /health."""
    status: str
    model_loaded: bool


class SubmitCorrectionRequest(BaseModel):
    """Request body for POST /corrections."""
    publication_id: int = Field(..., description="ID of the publication being corrected")
    assigned_cluster_id: int = Field(..., description="Cluster ID assigned by the algorithm")
    correct_cluster_id: int = Field(..., description="Correct cluster ID per human feedback")
    corrected_by: str = Field(default="unknown", description="Username or identifier of the corrector")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Confidence score for the correction")


class CorrectionResponse(BaseModel):
    """Response body for POST /corrections."""
    publication_id: int
    assigned_cluster_id: int
    correct_cluster_id: int
    corrected_by: str
    confidence: float
    exemplars_seeded: bool = Field(..., description="Whether exemplars were seeded for correct cluster")


class ClusterMetricsResponse(BaseModel):
    """Cluster metrics for a single cluster."""
    cluster_id: int
    intra_cluster_mean_similarity: float | None = None
    member_count: int | None = None
    correction_rate_30d: float | None = None
    pending_inflow_rate: float | None = None
    centroid_drift: float | None = None
    last_label_updated_at: datetime | None = None
    exemplar_coverage: float | None = None
    computed_at: datetime | None = None


class SystemConfig(BaseModel):
    """System configuration parameters."""
    SIMILARITY_THRESHOLD: float
    SOFT_SIMILARITY_THRESHOLD: float
    HDBSCAN_MIN_CLUSTER_SIZE: int
    STABLE_ID_SIMILARITY_THRESHOLD: float
    DYNAMIC_THRESHOLD_MULTIPLIER: float
    MIN_ASSIGNMENT_THRESHOLD: float
    MAX_ASSIGNMENT_THRESHOLD: float
    PENDING_RECLUSTER_ATTEMPTS: int
    RECLUSTER_MIN_NEW_PAPERS: int
    RECLUSTER_PENDING_THRESHOLD: int
    RECLUSTER_MAX_INTERVAL_HOURS: int
    CAH_L1_COUNT: int
    CAH_L2_COUNT: int
    CORRECTION_WINDOW_DAYS: int
    CORRECTION_RATE_HIGH: float
    CORRECTION_RATE_LOW: float
    THRESHOLD_TIGHTEN_DELTA: float
    THRESHOLD_RELAX_DELTA: float


class SystemConfigUpdate(BaseModel):
    """Payload to update a system configuration."""
    key: str = Field(..., description="The configuration key (e.g., SIMILARITY_THRESHOLD)")
    value: str = Field(..., description="The configuration value as a string")


class CorrectionEntry(BaseModel):
    """A log entry for a classification correction."""
    id: int
    publication_id: int
    assigned_cluster_id: int
    correct_cluster_id: int
    corrected_by: str | None = None
    confidence: float | None = None
    timestamp: datetime


class TaxonomyClusterNode(BaseModel):
    """Leaf node in the taxonomy tree (an actual cluster)."""
    cluster_id: int
    label: str
    member_count: int


class TaxonomyL2Node(BaseModel):
    """L2 node in the taxonomy tree."""
    l2_id: int
    l2_label: str
    clusters: list[TaxonomyClusterNode]


class TaxonomyL1Node(BaseModel):
    """L1 node in the taxonomy tree."""
    l1_id: int
    l1_label: str
    l2_nodes: list[TaxonomyL2Node]


class TaxonomyTreeResponse(BaseModel):
    """Full taxonomy tree response."""
    l1_nodes: list[TaxonomyL1Node]
    unassigned_clusters: list[TaxonomyClusterNode]
