"""
Pydantic request/response models for the classification API.
"""

from pydantic import BaseModel, Field


class ClassifyRequest(BaseModel):
    """Request body for POST /classify."""
    publication_id: int = Field(..., description="ID of the publication in the main database")
    title: str = Field(..., description="Publication title")
    abstract_text: str = Field(..., description="Publication abstract text")
    domain: str | None = Field(None, description="Domain name chosen by the author")
    pdf_url: str | None = Field(None, description="URL of the PDF file for text extraction")


class PersonalizedRecommendationRequest(BaseModel):
    """Request body for POST /recommend/personalized."""
    upvotedIds: list[int]
    downvotedIds: list[int]
    limit: int = 10


class CategoryPrediction(BaseModel):
    category: str
    confidence: float
    reason: str


class ClassifyResponse(BaseModel):
    """Response body for POST /classify."""
    publication_id: int
    cluster_id: int
    cluster_label: str
    confidence: float = Field(..., ge=0.0, le=1.0, description="Cosine similarity to cluster centroid")
    categories: list[CategoryPrediction] = Field(default_factory=list, description="Categories predicted by Gemma 3")
    keywords: list[str] = Field(default_factory=list, description="Keywords generated by Gemma 3")
    suggested_cluster_id: int | None = Field(default=None, description="Soft-assigned cluster ID for UI if outlier.")
    suggested_cluster_label: str | None = Field(default=None, description="Soft-assigned cluster label for UI if outlier.")


class RecommendationResponse(BaseModel):
    """Response body for recommendation endpoints."""
    publication_id: int
    similarity_score: float
    cluster_id: int | None = None


class ClosePair(BaseModel):
    """Response body for close pair detection."""
    publication_1_id: int
    publication_2_id: int
    similarity_score: float


class ClusterInfo(BaseModel):
    """Information about a single cluster."""
    cluster_id: int
    label: str
    member_count: int


class ClusterDetail(BaseModel):
    """Detailed cluster info with member publication IDs."""
    cluster_id: int
    label: str
    member_count: int
    publication_ids: list[int]


class ReclusterResponse(BaseModel):
    """Response body for POST /recluster."""
    total_publications: int
    clusters_found: int
    noise_points: int


class HealthResponse(BaseModel):
    """Response body for GET /health."""
    status: str
    model_loaded: bool
